<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite2" duration-ms="553334" started-at="2015-06-14T15:29:27Z" finished-at="2015-06-14T15:38:40Z">
    <groups>
      <group name="Prod">
        <method signature="NewTest.testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testAddDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testControl" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testDeleteDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testLogin()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogin" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogout" class="test.java.CloudTest.NewTest"/>
      </group> <!-- Prod -->
      <group name="Dev">
        <method signature="NewTest.testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testAddDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testControl" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testDeleteDevice" class="test.java.CloudTest.NewTest"/>
        <method signature="NewTest.testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogout" class="test.java.CloudTest.NewTest"/>
      </group> <!-- Dev -->
    </groups>
    <test name="ProdTest" duration-ms="553334" started-at="2015-06-14T15:29:27Z" finished-at="2015-06-14T15:38:40Z">
      <class name="test.java.CloudTest.NewTest">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="BeforeTest" is-config="true" duration-ms="330" started-at="2015-06-14T18:29:27Z" finished-at="2015-06-14T18:29:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="27134" started-at="2015-06-14T18:29:27Z" finished-at="2015-06-14T18:29:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogin() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogin" duration-ms="10405" started-at="2015-06-14T18:29:55Z" finished-at="2015-06-14T18:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="1" started-at="2015-06-14T18:30:05Z" finished-at="2015-06-14T18:30:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=SUCCESS method=NewTest.testLogin()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogin() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="259" started-at="2015-06-14T18:30:05Z" finished-at="2015-06-14T18:30:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="13986" started-at="2015-06-14T18:30:05Z" finished-at="2015-06-14T18:30:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testAddDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testAddDevice" duration-ms="23299" started-at="2015-06-14T18:30:19Z" finished-at="2015-06-14T18:30:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test.java.CloudTest.NewTest.testAddDevice(NewTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddDevice -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="3393" started-at="2015-06-14T18:30:42Z" finished-at="2015-06-14T18:30:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testAddDevice status=FAILURE method=NewTest.testAddDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testAddDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="266" started-at="2015-06-14T18:30:46Z" finished-at="2015-06-14T18:30:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="25640" started-at="2015-06-14T18:30:46Z" finished-at="2015-06-14T18:31:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testDeleteDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testDeleteDevice" duration-ms="6370" started-at="2015-06-14T18:31:12Z" finished-at="2015-06-14T18:31:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test.java.CloudTest.NewTest.testDeleteDevice(NewTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteDevice -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="3116" started-at="2015-06-14T18:31:18Z" finished-at="2015-06-14T18:31:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testDeleteDevice status=FAILURE method=NewTest.testDeleteDevice()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testDeleteDevice() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="254" started-at="2015-06-14T18:31:21Z" finished-at="2015-06-14T18:31:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="14347" started-at="2015-06-14T18:31:22Z" finished-at="2015-06-14T18:31:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogout() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testLogout" duration-ms="5982" started-at="2015-06-14T18:31:36Z" finished-at="2015-06-14T18:31:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test.java.CloudTest.NewTest.testLogout(NewTest.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogout -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="3460" started-at="2015-06-14T18:31:42Z" finished-at="2015-06-14T18:31:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogout status=FAILURE method=NewTest.testLogout()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testLogout() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="928" started-at="2015-06-14T18:31:45Z" finished-at="2015-06-14T18:31:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="setUp" is-config="true" duration-ms="15054" started-at="2015-06-14T18:31:46Z" finished-at="2015-06-14T18:32:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testControl() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="testControl" duration-ms="395844" started-at="2015-06-14T18:32:01Z" finished-at="2015-06-14T18:38:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test.java.CloudTest.tests.Control.execute(Control.java:77)
	at test.java.CloudTest.NewTest.testControl(NewTest.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testControl -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="takeScreenShotOnFailure" is-config="true" duration-ms="2953" started-at="2015-06-14T18:38:37Z" finished-at="2015-06-14T18:38:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testControl status=FAILURE method=NewTest.testControl()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void test.java.CloudTest.NewTest.testControl() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:test.java.CloudTest.NewTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="285" started-at="2015-06-14T18:38:40Z" finished-at="2015-06-14T18:38:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- test.java.CloudTest.NewTest -->
    </test> <!-- ProdTest -->
  </suite> <!-- TestSuite2 -->
</testng-results>
